services:
  app:
    build:
      context: .
      dockerfile: docker-config/php/Dockerfile
    container_name: myportfolio-php
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db

  web:
    image: nginx:1.27-alpine
    container_name: myportfolio-nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  node:
    image: node:20-alpine
    container_name: myportfolio-node
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: myportfolio-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:

